---
linters-settings:
  misspell:
    locale: US
  errorlint:
    # Report non-wrapping error creation using fmt.Errorf
    errorf: false

linters:
  enable:
    - bodyclose
    - dupl
    - errorlint
    - goconst
    - gosec
    - misspell
    - unconvert
    - prealloc
  disable:
    - errcheck
    - ineffassign

issues:
  exclude-rules:
    - path: _test.go
      linters:
        - dupl
        - funlen

run:
  skip-dirs:
    - concurrent/*
    - health/*
    - server/*
    - service/*
    - webhook/aws/*
    - xviper/*
    - xmetrics/*